### PR TITLE
Improve UX & Performance

### PR DESCRIPTION
**Pull request by wagrenier**
* Added shortcuts for: `Load Comments`, `Export Disassembly`, `Show as Hex`, `Search Memory`, `Dump Memory`, `Goto`
* Moved many rarely used UI to the MenuBar to optimize space
* Added new vector font
* Enable font scaling slider
* Limit fps through tick rates (also a slider for it)
* Improve performance by up to 50% by converting raw instructions into a string only once rather than on each frame rendering
* Use new Table API
* Switch to using screen % instead of pixel values to make UI more scaleable on various DPI 

https://github.com/chaoticgd/vutrace/assets/16808836/8a9119ef-a1f2-476c-aeaa-508e75c5fbc0

### CODE REVIEW

**Comment by chaoticgd** [comment]
Good features, but there's a number of issues, roughly sorted from most important to least important:

- Epilepsy warning: https://github.com/chaoticgd/vutrace/assets/43898262/9e678e82-c6d7-4496-837e-183053d6bb07
- The shortcuts don't seem to work very well. I think this is related to you checking that ImGuiKey_LeftCtrl went from up to down on the same frame as the letter keys. You should use IsKeyDown for the ctrl check instead.
- It looks like it isn't actually re-rendering the font when you change the size, it's just scaling the already rendered bitmap version.
- The line input dialogs don't scale with the size of the fonts making them unusable.
- It would be nice for the default font size to be closer to what it was before, like what is currently labeled as 0.8. The current default is a bit hard to use on my 1080p display.
- An option to use the built-in bitmap font again would be nice.
- It isn't clear just from the UI what the "App Refresh Rate" slider does exactly.
- It looks like you accidentally reverted this [71900b06cc8c9bcf3bdc58ef09be7319863c305b](https://github.com/chaoticgd/vutrace/commit/71900b06cc8c9bcf3bdc58ef09be7319863c305b) while merging.
- Again, very large diffs caused by the same kinds of formatting mistakes discussed with the previous PR. For example if you don't change it back it'll make git blame harder to use, so you won't be able to see which commits edited which lines as easily.
- Don't worry about the messy git history. I can just do a squash commit so it doesn't affect the master branch.

**Comment by wagrenier** [comment]
I'll review all of that. What OS are you on so I can try to test it there? The shortcuts worked well on my OS/kb.

For the font scaling, there were some complications for re-rendering the font. I'll see if I can work around those limitations now that the font is embedded.

**Comment by chaoticgd** [comment]
> What OS are you on so I can try to test it there? The shortcuts worked well on my OS/kb.

Kubuntu 22.04. You should be able to implement the change I suggested as-is for the shrotucts.

**Comment by chaoticgd** [comment]
For the flickering thing I would make it so the font scale only applies when the mouse goes up on the slider.

**Comment by wagrenier** [comment]
Todos (I'll update the list as the changes get pushed):
- [ ] Fix shortcuts with `IsKeyDown` for `Ctrl` key
- [ ] Rebuild font atlas when changing font size
- [ ] Option to use original font
- [ ] Font size slider only updates upon release
- [ ] Fix code reverted
- [ ] Fix code formatting
- [ ] Clearer impact of refresh rate menu

**Comment by wagrenier** [comment]
> line input dialogs don't scale with the size of the fonts making them unusable

Regarding that, with a rebuild of the font atlas I believe it has fixed this issue. I am unsure as I do not see any issues with it.

I added a tooltip for the application refresh rate, currently the message is `Limits the application's refresh rate to decrease impact on CPU. Assuming a 60Hz monitor, the default value (1) is enough.
0 is unlimited, 60Hz / 2 = 30fps, 60Hz / 3 = 20fps, etc.`

I believe I implemented all the changes you requested except for the code format. Once everything is ok with you, I'll proceed to that.

**Comment by wagrenier** [comment]
An updated video featuring the requested features:

https://github.com/chaoticgd/vutrace/assets/16808836/4949eda3-d5fa-4dce-bc92-bf9f9818a38a

**Pull request merged**
